title: CP Course Level 1
description: "A starter course in competitive programming"
theme: minima
markdown: kramdown

url: "https://okhalifa-official.github.io"
baseurl: "/CP_Course.Lv1"

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
